import type { MetadataRoute } from "next";

// Web App Manifest — installable PWA + the metadata an iOS WebView/home-screen
// shortcut reads. Next auto-injects <link rel="manifest"> from this file.
// (Native iOS app icons are handled by Capacitor in Phase 2; here we point at
//  the existing SVG mark, which renders crisply at any size.)
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Countrivo — Geography Games",
    short_name: "Countrivo",
    description:
      "Play 17 geography games. Daily challenges, flag quizzes, country rankings and strategy puzzles. 243 countries.",
    id: "/",
    start_url: "/games",
    scope: "/",
    display: "standalone",
    orientation: "portrait",
    background_color: "#10141b",
    theme_color: "#10141b",
    categories: ["games", "education", "trivia"],
    icons: [
      {
        src: "/favicon.svg",
        sizes: "any",
        type: "image/svg+xml",
        purpose: "any",
      },
      // 180×180 PNG generated by app/apple-icon.tsx — home-screen icon for
      // platforms that don't render SVG icons.
      {
        src: "/apple-icon",
        sizes: "180x180",
        type: "image/png",
      },
    ],
  };
}
